development:
  adapter: sqlite3
  database: db/development.sqlite3
  timeout: 5000

test: &TEST
  adapter: sqlite3
  database: db/development.sqlite3
  timeout: 5000

production:
  adapter: sqlite3
  database: db/development.sqlite3
  timeout: 5000

cucumber:
  <<: *TEST